### ISSUE TITLE
Sidebars are failing, please help

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Feinstein-Center-for-American-Jewish-History#1]
Hey the sidebars are failing like for CJTP. I have attached a screenshot of the Travis fail, it's something in the layout.. I have removed them for the time being.

**Comment by CVE82** [comment]
![image](https://user-images.githubusercontent.com/15130721/44425854-1358e500-a55b-11e8-9239-d6bd0500fed1.png)

**Comment by tu-chill** [comment]
i took the screen shot out

**Comment by tu-chill** [comment]
sidebars are in.
