### ISSUE TITLE
Please center hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Feinstein-Center-for-American-Jewish-History#3]
Hey Zac attack can you center or resize their center's banner as the hero image? Trying to go live with this baby today! Thanks!

**Comment by ZMcGroarty** [comment]
![feinstein-hero-min](https://user-images.githubusercontent.com/15017242/44736375-0c7f2480-aabd-11e8-97aa-ddae11ab77a9.png)

**Comment by CVE82** [comment]
![image](https://user-images.githubusercontent.com/15130721/44736587-9fb85a00-aabd-11e8-9ee5-05a36bb79e99.png)

Thank you so much Speedy Gonzales!!

**Comment by CVE82** [comment]
Hey Zac Attack the banner is cutting off, would you be able to resize when you have a chance? Please and thank you?

![image](https://user-images.githubusercontent.com/15130721/44789564-e2843b80-ab6a-11e8-91f8-51fefc500d08.png)

**Comment by ZMcGroarty** [comment]
Lets see if this one fits

![feinstein-hero-min](https://user-images.githubusercontent.com/15017242/44789764-7524da80-ab6b-11e8-848f-b89a9060a160.png)

**Comment by CVE82** [comment]
Thanks so much going to try now!

**Comment by CVE82** [comment]
Perfection, thank you!
