### ISSUE TITLE
News Landing Page is not displaying correctly

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Feinstein-Center-for-American-Jewish-History#4]
Hey WC, the news landing page for Feinstein is not displaying properly in Drupal.

**Comment by tu-chill** [comment]
Drupal -> Views -> Feinstein -> news page -> Row style options -> panel layout = responsive rows
Conten:t Post date = Top
Content: Title = Top
Content: Feature Image = Center
Content: Body = Bottom
Program = Bottom 

*We may not be bringing in the node reference for centers.

**Comment by tu-chill** [comment]
![screen shot 2018-09-13 at 3 07 45 pm](https://user-images.githubusercontent.com/12816361/45510631-c4bcf600-b768-11e8-9166-0452e17f9645.png)
![screen shot 2018-09-13 at 3 08 55 pm](https://user-images.githubusercontent.com/12816361/45510637-cab2d700-b768-11e8-8483-9f6cb345e705.png)

**Comment by CVE82** [comment]
Oh shit I forgot to go back and change that row setting, my bad! Thank you so much!!
